### ISSUE TITLE
Add support to check if remote side is using ice-lite

### ISSUE THREAD

**Issue by xnorpx** [algesten/str0m#152]
- Parse SDP to check if remote side is using ice-lite
- add back functionality in agent.rs to check for binding req.

**Comment by algesten** [comment]
Is the idea that str0m would "undo" its own ice-lite setting if the remote side also declares ice-lite?

**Comment by xnorpx** [comment]
I forgot the context tbh. but looking into it now it seems that it's fine two have 2 peers in ice-lite mode. So this is probably a non-issue. If it's an issue I am sure it will resurface.
