### ISSUE TITLE
Make minimum DTLS version configurable

### ISSUE THREAD

**Issue by algesten** [algesten/str0m#156]
By default we should disallow DTLS 1.0. To do this we need a PR to land in rust-openssl crate: https://github.com/sfackler/rust-openssl/pull/1886

The man page in openssl: https://www.openssl.org/docs/man3.1/man3/DTLSv1_2_method.html - tells us `DTLSv1_2_method` is deprecated. The way to limit the DTLS version (or TLS for that matter), is to use `SSL_CTX_set_min_proto_version`. In the Rust wrapper of openssl this corresponds to https://docs.rs/openssl/0.10.50/openssl/ssl/struct.SslContextBuilder.html#method.set_min_proto_version however `SslVersion` constant lacks the values we need: https://docs.rs/openssl/0.10.50/openssl/ssl/struct.SslVersion.html

**Comment by xnorpx** [comment]
Should be released now?

https://docs.rs/openssl/0.10.54/openssl/ssl/struct.SslVersion.html

**Comment by algesten** [comment]
It's not configurable yet. We do lock it down however.

**Comment by algesten** [comment]
Let's continue this in #326
