### ISSUE TITLE
Datachannel reliable mode hashmap performance

### ISSUE THREAD

**Issue by xnorpx** [algesten/str0m#182]
This might belong to the SCTP crate, but I will put it here for now for visibility.

When running data channels in reliable mode I saw hash map being on top in the performance.

Switching the datachannel to unreliable made it better.

![image](https://github.com/algesten/str0m/assets/302709/b65c6fb9-588d-4bae-a7c9-c07c05ce8853)

```rust
   _ = self.rtc.direct_api().create_data_channel(ChannelConfig {
                            label: "".into(),
                            negotiated: Some(1337),
                            ordered: true,
                            reliability: Reliability::Reliable,
                            ..Default::default()
                        });
```

**Comment by algesten** [comment]
Do you know how much packet loss you have here?

**Comment by xnorpx** [comment]
I don't have the stats for that currently, but given that I have no packetloss on 9 audio and 9 video streams my guess it's 0 for data channel as well. But I would need to verify this.

**Comment by xnorpx** [comment]
I wonder if #216 is the cause of this one as well? I will profile it once I get back to work.

**Comment by algesten** [comment]
Did you get anywhere with this?

**Comment by xnorpx** [comment]
I will do new profiling once back from vacation, see if the ack fix makes it better.

**Comment by xnorpx** [comment]
I can no longer reproduce this with reliable data channels so most likely #215 fixed it. Closing
