### ISSUE TITLE
Fuzzy Codec Matching

### ISSUE THREAD

**Issue by k0nserv** [algesten/str0m#187]
Firefox cannot negotiate an Opus track with str0m atm but I think it should be possible.

The reason for this is that Firefox produces the following `CodecSpec`

```rust
 CodecSpec {
    codec: Opus,
    clock_rate: 48000,
    channels: Some(
        2,
    ),
    format: FormatParams {
        min_p_time: None,
        use_inband_fec: Some(
            true,
        ),
        level_asymmetry_allowed: None,
        packetization_mode: None,
        profile_level_id: None,
        profile_id: None,
    },
}
```

That str0m tries to [match exactly](https://github.com/algesten/str0m/blob/e730f6d837759270072e11c1368130d23cad0353/src/format.rs#L189) against 

```rust
  CodecSpec {
    codec: Opus,
    clock_rate: 48000,
    channels: Some(
        2,
    ),
    format: FormatParams {
        min_p_time: Some(
            10,
        ),
        use_inband_fec: Some(
            true,
        ),
        level_asymmetry_allowed: None,
        packetization_mode: None,
        profile_level_id: None,
        profile_id: None,
    },
}
}
```

I think in this case str0m should accept the match despite the `min_p_time` value not being specified by Firefox, unsure how it should default.

There's a [TODO comment](https://github.com/algesten/str0m/blob/e730f6d837759270072e11c1368130d23cad0353/src/format.rs#L192) about this.

**Comment by k0nserv** [comment]
I'm trying to figure out if the logic for fuzzy matching is specific in some RFC

**Comment by k0nserv** [comment]
Initial stab at this for audio: https://github.com/algesten/str0m/pull/189

**Comment by algesten** [comment]
Nice!

**Comment by morajabi** [comment]
love this, I was actually wondering why FF didn't work.

**Comment by algesten** [comment]
There's more fuzziness to do for video etc. Let's raise separate issues/PR for each thing.
