### ISSUE TITLE
Add support for GCM cipher suites for DTLS-SRTP

### ISSUE THREAD

**Issue by xnorpx** [algesten/str0m#193]
Opening issue so we don't lose track.

It said that SRTP_AEAD_AES_128_GCM has lower complexity than SRTP_AES128_CM_SHA180

Context from Zullip discussion. 

+ const DTLS_SRTP: &str = "SRTP_AES128_CM_SHA1_80;SRTP_AEAD_AES_128_GCM";
- const DTLS_SRTP: &str = "SRTP_AES128_CM_SHA1_80";
then we'd be negotiating both, however we'd also need to implement GCM support but OpenSSL supports it so shouldn't be too challenging

**Comment by xnorpx** [comment]
@k0nserv @algesten  this one can be closed now?

**Comment by k0nserv** [comment]
Yep, good call!
