### ISSUE TITLE
DCEP message type mismatches with the RFC standard

### ISSUE THREAD

**Issue by biceneutron** [algesten/str0m#215]
When I initiated a data channel in a webrtc-rs client and try to establish the data channel connection with str0m server, I got this error message from webrtc-rs:
```
ERROR webrtc_data::data_channel] Failed to handle DCEP: Util(Std(StdError(InvalidMessageType(1))))
```

The cause is that, now the `DATA_CHANNEL_ACK ` message type of DCEP messages is defined as `0x01` in str0m. But according to [RFC 8832](https://datatracker.ietf.org/doc/rfc8832/#:~:text=DATA_CHANNEL_ACK%20%20%7C%200x02%20%20%20%20%20%20%7C%20RFC%208832), this type should be `0x02`.

**Comment by algesten** [comment]
Good one!

I'm amazed data channels work in str0m at all. We use this in production! 🙈
