### ISSUE TITLE
RTP packet is never resend when received NACK

### ISSUE THREAD

**Issue by giangndm-bluesea** [algesten/str0m#236]
https://github.com/algesten/str0m/blob/2627fcbfaaa78a925b2a87b695e3a236ef7555b8/src/streams/send.rs#L422-L428

self.rtx_pt is never set then the above logic never passes cause the RTP packet doesn't resend when received NACK

**Comment by algesten** [comment]
@giangndm-bluesea thanks! What is the situation when this doesn't work?

Are you using sdp_api or direct_api?

**Comment by giangndm-bluesea** [comment]
@algesten Thank you for the awesome library, I am working on an SFU project then I using rtp_mode with direct_api to send each RTP packet one by one. With sdp_api, I am only used for creating answer with input offer.

**Comment by algesten** [comment]
@giangndm-bluesea Thanks for reporting this. I think it's fixed in main.

**Comment by giangndm-bluesea** [comment]
@algesten thank you for your very fast response. I will check at my side
