### ISSUE TITLE
Chat demo breaks on high bitrate

### ISSUE THREAD

**Issue by alexlapa** [algesten/str0m#310]
So i'm testing str0m's chat demo in a single producer single consumer scenario with a modified client side for a higher bitrate video. Client changes look like this:

```javascript
        async function startCam() {
            // ...
            streamCam = await navigator.mediaDevices.getUserMedia({
                video: {
                    width: 1920,
                    height: 1080,
                },
            });
            // ...
            const parameters = tr.sender.getParameters();
            parameters.encodings[0].maxBitrate = 99000000;
            tr.sender.setParameters(parameters);

            await negotiate();
        }
```

And server side is unmodified. At some point, around 1.5k packets per second i stop receiving video on a receiver, and this error is printed to logs:
```
WARN chat: Client (1) failed: WriteWithoutPoll
INFO str0m: Set alive=false
```

This error happens in a `handle_media_data()` function, right here:
```rust
if let Err(e) = writer.write(pt, data.network_time, data.time, &data.data) {
    warn!("Client ({}) failed: {:?}", *self.id, e);
    self.rtc.disconnect();
}
```

I have tried commenting out `disconnect()` call, in this case this `WriteWithoutPoll` error keeps firing few hundred times per second and the video is becoming corrupted.

So i'm wondering what should be the problem here. Str0m looks like it should be able to handle any amount of load as far as there is enough cpu. May it be that this issues comes from the chat demo code?

**Comment by algesten** [comment]
Hi! Thanks for trying str0m!

That error means we are somehow ending up doing two consecutive writes without letting the internal state flush through from `poll_output()`.

And I think you just found a bug in the chat.rs example.

https://github.com/algesten/str0m/blob/main/examples/chat.rs#L186

This can't be a for-loop because we're only allowed to do one write before we need to run the "outer loop": https://github.com/algesten/str0m/blob/main/examples/chat.rs#L128

**Comment by algesten** [comment]
As a quick fix you can try removing that for-loop with just popping a single value at a time.

**Comment by alexlapa** [comment]
@algesten ,

Thanks for the quick response.

> That error means we are somehow ending up doing two consecutive writes without letting the internal state flush through from poll_output().

I am not sure this to be the case. I've added some additional logs, next to `writer.write()` , `rtc.poll_output()` and `writer.request_keyframe()` calls. And the output looks like this:

```
ERROR chat: Client (0) poll_output
ERROR chat: Client (1) poll_output
ERROR chat: Client (1) writer.write
ERROR chat: Client (0) poll_output
ERROR chat: Client (1) poll_output
ERROR chat: Client (1) writer.write
WARN chat: Client (1) failed: WriteWithoutPoll
```

And another interesting fact that i've noticed is that the video is starting to corrupt before `WriteWithoutPoll` is fired. In this test run the video started to corrupt around 1.2k packets per second and `WriteWithoutPoll` + `rtc.disconnect()` happened around 1.8k pps.

**Comment by algesten** [comment]
@alexlapa that output looks exactly what I expect for this error.

```
ERROR chat: Client (1) poll_output
ERROR chat: Client (1) writer.write
                                                               <--------- need poll_output here
WARN chat: Client (1) failed: WriteWithoutPoll
```

**Comment by alexlapa** [comment]
@algesten ,

I don't see two consecutive write calls, `Client (1) writer.write` is logged before doing `writer.write()`. I've also tweaked `handle_media_data` function a little bit to make sure that the `Rtc` we are going to write to is exhausted, so my `handle_media_data` currently looks like this:

```rust
fn handle_media_data(&mut self, origin: ClientId, data: &MediaData, socket: &UdpSocket) {
    // Figure out which outgoing track maps to the incoming media data.
    let Some(mid) = self.tracks_out
        .iter()
        .find(|o| o.track_in.upgrade().filter(|i|
            i.origin == origin &&
            i.mid == data.mid).is_some())
        .and_then(|o| o.mid()) else {
            return;
        };

    loop {
        error!("Client ({}) poll_output", *self.id);
        let poll = self.rtc.poll_output().unwrap();
        match poll {
            Output::Timeout(_) => {
                break
            }
            Output::Transmit(transmit) => {
                socket
                    .send_to(&transmit.contents, transmit.destination)
                    .expect("sending UDP data");
            }
            Output::Event(_) => {
                unreachable!();
            }
        }
    }

    assert!(matches!(self.rtc.poll_output().unwrap(), Output::Timeout(_)));

    let Some(writer) = self.rtc.writer(mid) else {
        return;
    };

    // Match outgoing pt to incoming codec.
    let Some(pt) = writer.match_params(data.params) else {
        return;
    };

    error!("Client ({}) writer.write", *self.id);
    if let Err(e) = writer.write(pt, data.network_time, data.time, &data.data) {
        warn!("Client ({}) failed: {:?}", *self.id, e);
        std::process::exit(0);
        self.rtc.disconnect();
    }
}

``` 

But with no luck, log output looks like this:

```
ERROR chat: Client (1) poll_output
ERROR chat: Client (1) poll_output
ERROR chat: Client (1) writer.write
ERROR chat: Client (0) poll_output
ERROR chat: Client (1) poll_output
ERROR chat: Client (1) poll_output
ERROR chat: Client (1) writer.write
WARN chat: Client (1) failed: WriteWithoutPoll

```

**Comment by algesten** [comment]
I'll try and rig this locally.

**Comment by algesten** [comment]
@alexlapa I can't get the problem locally, would you mind testing with this fix? https://github.com/algesten/str0m/pull/312

**Comment by alexlapa** [comment]
@algesten ,

> would you mind testing with this fix? https://github.com/algesten/str0m/pull/312

That fixed it.

Another thing that worked is calling `rtc.handle_input(Input::Timeout(Instant::now()))` before each `rtc.writer(mid).write()` call.

**Comment by alexlapa** [comment]
So since https://github.com/algesten/str0m/pull/312 is merged and I'm not sure whether this problem needs some additional tinkering i believe that this issue can be closed.

**Comment by algesten** [comment]
Thanks!
