### ISSUE TITLE
Keeping a TURN allocation alive

### ISSUE THREAD

**Issue by thomaseizinger** [algesten/str0m#325]
When interacting with a TURN server, allocations and permissions need to be refreshed regularly, otherwise they expire. Is it in scope for `str0m` to operate such a state machine?

**Comment by algesten** [comment]
Good question.

In my mind TURN and STUN servers have been completely outside of str0m's purview. str0m has got the notion of host, relay and server/peer-reflexive ice candidates, since you need to know the type to make pairs that matches that of the remote peer (which is what the [README says](https://github.com/algesten/str0m#nic-enumeration-and-turn-and-stun) pretty much). But I'm open to debate.

I haven't got in my head the exact interactions with TURN (and STUN servers?). What would the benefits be of having the state machine in str0m?

**Comment by thomaseizinger** [comment]
> What would the benefits be of having the state machine in str0m?

Roughly, the way TURN works is:

- Make an allocation: This allocates an IP4 and/or IP6 port on the relay that somebody can send data to and and it will be relayed to you.
- Bind a channel: A channel is a 4-byte framing mechanism that allows multiplexing of an allocation to a particular peer. This avoids the heavy framing of STUN messages.

Both of these concepts need to be refreshed at a certain interval, otherwise the TURN server will free them (even if they are heavily in use.)

`str0m` already knows the concept of TURN servers as part of the ICE candidate process. What could be useful is to build a functionality of configuring one or more TURN server in `str0m` and extend the state machine such that:

- It emits STUN requests to figure out ones' external IP
- If hole-punching fails, automatically falls back to a relay by emitting an allocation
- Keeps an allocation and or channel binding alive if it is in use

**Comment by algesten** [comment]
str0m's ICE implementation is me following the relevant RFCs and making some tweaks. I documented [it here](https://github.com/algesten/str0m/blob/main/docs/ice.md)

@pthatcher said previously that libWebRTC ICE module is the best in class, and str0m would be well served by translating that code line-by-line to str0m. As far as I know there is nothing particularly wrong with str0m's ICE, but it could be even better – especially for the peer-to-peer case (which I myself isn't actively using).

@thomaseizinger with that in mind, would you say it would be worth building TURN/STUN on top of str0m's existing ICE, or should we go back to square one to ensure the peer-to-peer is as good as it possibly can be?

**Comment by thomaseizinger** [comment]
> @thomaseizinger with that in mind, would you say it would be worth building TURN/STUN on top of str0m's existing ICE, or should we go back to square one to ensure the peer-to-peer is as good as it possibly can be?

I don't think we'd need to go back to square one. The thing is, str0m already deals with timers etc internally so extended the scope to tracking TURN allocations wouldn't be too far fetched I think? Also, the process of discovering addresses via STUN is well-specified so I am not sure how anybody would want anything different (which IMO is a very valid reason to not include such behaviour in a low-level library).

The The integration would obviously remain SANS-IO but I'd imagine something like adding two configuration options to an `Rtc` instance: STUN servers and TURN servers.

If a STUN server is present, we'd automatically emit an event that is a binding request to the STUN servers IP and add a function to pass the response back. This would internally add the address as a candidate.

Similarly, if a TURN server is present, str0m would emit an event that creates an allocation in case all previous candidates failed to establish a connection. Once created, it can keep track of it internally and refresh the allocation & channel binding to make sure it stays operational.

**Comment by morajabi** [comment]
@algesten having implemented TURN + STUN client for str0m, I think most gain is in making the internal str0m ICE better. The former is a one-time thing that doesn't involve many details except for handling allocations and forwarding packets. But the ICE mechanics directly impact how reliable all 3 connections are (host, srflx, relay).

**Comment by thomaseizinger** [comment]
> @algesten having implemented TURN + STUN client for str0m

Is that open-source somewhere? :)

**Comment by algesten** [comment]
Related to #413

**Comment by thomaseizinger** [comment]
I am going to close this as I've come to the conclusion that it depends too much on the particular application what would be desired from such an implementation. For example, we now model allocations and channel bindings as RAII guards but that is not necessarily something everybody would want I imagine.

**Comment by morajabi** [comment]
> > @algesten having implemented TURN + STUN client for str0m
> 
> Is that open-source somewhere? :)

No it's not as I don't think it's anything special. I use webrtc_rs for TURN allocations.
