### ISSUE TITLE
No way to choose `VP9 SVC layer` 

### ISSUE THREAD

**Issue by logist322** [algesten/str0m#404]
I'm trying to use **str0m** with **VP9 SVC** and I have found that there is no opportunity to choose **SVC layers** from the emitted `MediaData`. 

I have some propositions how to solve it:
- add a scheme of `MediaData::data` in `Vp9CodecExtra` for manual constructing preferred **SVC layers**,
- add some methods on `MediaData` that configure `MediaData::data` for preferred **SVC layer**,
- emit `MediaData` not for the all **SVC layers**,  but for the very **SVC layer**.

Let`s choose what to do and I will implement it!

**Comment by davibe** [comment]
I think the current approach would be the 1st one you mentioned. Unless you see issues with it

**Comment by logist322** [comment]
@davibe Thanks for your quick answer!

**Comment by algesten** [comment]
@davibe do we have any example of how this would look?

**Comment by logist322** [comment]
@algesten If you want you can take a look at [_my drafts_](https://github.com/algesten/str0m/compare/main...logist322:str0m:svc-mapping?diff=unified). Of course, it is minimal dirty prototype, but it has been already working with our media server.

**Comment by logist322** [comment]
@algesten The max size is 9 (9 layers for S3T3/L3T3 cases).

**Comment by davibe** [comment]
@logist322 this can be closed, right ?
