### ISSUE TITLE
Don't panic on message from unknown socket

### ISSUE THREAD

**Issue by thomaseizinger** [algesten/str0m#467]
> This took me down a rabbit hole. Reading the code it's not clear to me what the exact semantics of discarding a client is. I was wondering whether this change is correct, or whether the check should be in the `let local_idx = …` above.
> 
> I'm leaning towards that your change is correct – this leaves the candidate as known for incoming traffic (not triggering the `STUN request for socket that is neither a host nor a relay candidate.` expect).

When reading the code, I noticed that `discarded` has a double meaning. It means both invalidated and redundant. Perhaps that can be clarified at some point by just not adding redundant candidates at all?

Also, the panic you are talking about is actually something that I think we should fix. I don't think we should put it on the application to sanitise these inputs. Instead, str0m should just discard the message I think.

_Originally posted by @thomaseizinger in https://github.com/algesten/str0m/issues/466#issuecomment-1968628659_

**Comment by algesten** [comment]
Is this still relevant?

**Comment by thomaseizinger** [comment]
Duplicate of https://github.com/algesten/str0m/issues/473.
