### ISSUE TITLE
Remove panic on missing candidates

### ISSUE THREAD

**Issue by thomaseizinger** [algesten/str0m#473]
The following panic can be triggered if the `IceAgent` is being fed "wrong" data: https://github.com/algesten/str0m/blob/eb0fbe0e01d04e38b8b230a9995951d38447750f/src/ice/agent.rs#L1166-L1168

I'd argue that we should remove this panic and instead just drop the message. This can for example be triggered if the `IceAgent` is not configured with a host candidate but only with srflx candidates. I don't really see why that wouldn't be valid?

Generally, I don't think we should ever panic if the user hands us bad socket addresses or data within `Receive` / `StunPacket`. I'd prefer if we log a `warn!` and drop the packet. We are after all exposed to network traffic here and should gracefully handle whatever is thrown at us.

**Comment by algesten** [comment]
Yeah, agree. Panic is a bit much. Dropping the packet seem reasonable.

**Comment by algesten** [comment]
This has been addressed right?

**Comment by thomaseizinger** [comment]
> This has been addressed right?

Nope! Not as far as I know.
