### ISSUE TITLE
Fuzzing

### ISSUE THREAD

**Issue by thomaseizinger** [algesten/str0m#474]
Recording this as an idea. Not sure how much time I'll be able to spend on it.

It would be nice to fuzz all parsing APIs to ensure panics cannot be triggered via network paths.

**Comment by algesten** [comment]
Should be fairly simple. The starting point for fuzzing is in place. See `run-fuzz.sh` in the root.

**Comment by thomaseizinger** [comment]
> Should be fairly simple. The starting point for fuzzing is in place. See `run-fuzz.sh` in the root.

Ha! I should have checked that. I was relying on my memory and that  is apparently older than 2 months 🙃
