### ISSUE TITLE
RTP level media API

### ISSUE THREAD

**Issue by algesten** [algesten/str0m#5]
The media API currently works only on "Sample" level, full H264/VP8/etc packets. The RTP level is an internal concern to str0m and there are built-in packetizer/depacketizer to go from sample level to RTP level. https://github.com/algesten/str0m/tree/main/packet

# The case against RTP level API

The WebRTC related RFC sometimes seem to consider SFU (Signal Forward Units) as something that just takes incoming RTP packets and routes them to other clients. This solves a quite narrow use case where not many peers participate in the same session.

RTP packets can't pass through an SFU unaltered because many RTP header fields depends on situation:

* Header extensions – negotiated in SDP, must be fulfilled specific to the peer-peer connection.
* Sequence numbers – must not be increased if you're not actively sending.
* TWCC (transport wide congestion control header) – must be set for entire peer.
* Bandwidth estimation / congestion control – must be handled for entire peer.
* PLI – if the sending peer has a bad connection, all downstream peers would shout PLI ("PLI storms" is a problem).
* Nacks and RTX resends – at the very least the original packets must be buffered to handle resends.

The above requires at least some level of rewriting the RTP header.

```
               Bad link                            ┌─────────────┐
                  │                                │             │
                  │                         ┌──────│  Sender 1   │
                  │                         │      │             │
┌─────────────┐   │    ┌─────────────┐      │      └─────────────┘
│             │   ▼    │             │      │                     
│  Receiver   │◀ ─ ─ ─ │     SFU     │◀─────┤                     
│             │        │             │      │                     
└─────────────┘        └─────────────┘      │      ┌─────────────┐
                                            │      │             │
                                            └──────│  Sender 2   │
                                                   │             │
                                                   └─────────────┘
```

The receiver here will miss different packets from Sender 1 and Sender 2. In a naive SFU, the NACK, PLI and FIR would be forwarded back to source. That means an increased pressure on bandwidth for all peers, not just the Receiver.

To make the SFU smarter, we can implement various levels of RTP buffering.

1. Buffer packets to handle NACK. This is very simple, just handle resends on the last leg (str0m does this internally).
2. Buffer packet sequences to handle some PLI/FIR without hitting the Sender. This requires a knowledge of what is a keyframe, which in turn requires us to reassemble RTP into Samples.

# Make an RTP level API

The above doesn't mean it's impossible to make an RTP level API. It just means the RTP level can't be thought of as "simply write this RTP packet to the wire". At the very least all headers must be fixed up to be correct given the SDP, TWCC etc.

I think we want a method to switch either an m-line, or the entire session into "RTP mode", which means instead of emitting `Event::MediaData(MediaData)`, we have another event such as `Event::RtpData(RtpData)`, and also  `MediaWriter::write_rtp` for the other direction.

**Comment by algesten** [comment]
Values that need rewriting:

* Payload type
* Sequence number
* Ssrc
* Transport CC sequence number
* Rid
* Rid repair
* Mid
* Absolute send time?

**Comment by pthatcher** [comment]
You also need to rewrite VP8 things like PictureID and TL0_PIC_IDX.

**Comment by algesten** [comment]
Maybe it's easier to turn it around. What values from the original RTP header _can we keep_?

* Padding bit
* Marker bit
* Timestamp

----

Question is what to do with RTP header extension values. Some things like video orientation and audio level would be nice to just keep, however they might change mapping between the RTP being provided vs what is negotiated with the remote peer.
