### ISSUE TITLE
How to learn nominated candidate?

### ISSUE THREAD

**Issue by thomaseizinger** [algesten/str0m#527]
This is a somewhat related problem to https://github.com/algesten/str0m/issues/525. Currently, `NominatedSend` event only includes the local `source` socket to send from.

In case a server-reflexive candidate gets nominated, the `source` address will be set to the server-reflexive candidate's `base` which is the same as a host candidate's address. So it is impossible to know whether the host or the server-reflexive candidate got nominated.

Would it make sense to emit the two candidates instead?

**Comment by algesten** [comment]
This is an abstraction. It deliberately does not try to tell you candidates. Instead it says "send to this IP from this IP". What candidates that might correspond to is an internal detail, since you would not have declared all of them (some are dynamically discovered).

Do you need to know the exact candidates?

**Comment by thomaseizinger** [comment]
> Do you need to know the exact candidates?

Currently, we are still invalidating candidates to achieve a smooth roaming of sockets that does not rely on waiting for the ICE timeout. In order to invalidate them, I need to loop over `local_candidates` and find the candidate again that got nominated. But in the case of host and server-reflexive candidates, that is ambiguous.

**Comment by lolgesten** [comment]
Alright. So if you are going down the ICE restart route. Would that change things?

**Comment by thomaseizinger** [comment]
> Alright. So if you are going down the ICE restart route. Would that change things?

A little bit. It would still be useful to know whether I am connected via a relay candidate or not. Sending from a relay candidate requires wrapping messages in channel data messages and sending them to an entirely different socket. To learn about that, I still need to search through the list of local candidates for the one I added.

I get the idea of the abstraction but I am not sure it makes much sense. If my input are candidates, then the output should maybe be as well? It is not like `IceAgent` can hide the concept of candidates from me.

**Comment by algesten** [comment]
I think this is "in spirit" with the spec (see other issue): https://github.com/algesten/str0m/issues/525#issuecomment-2157710261
