### ISSUE TITLE
Setting playout delay using `Writer`

### ISSUE THREAD

**Issue by UE2020** [algesten/str0m#542]
I see fields related to playout delay on the extension values struct, but how can they be set? There doesn't seem to be an API to do so.

**Comment by algesten** [comment]
> I see fields related to playout delay on the extension values struct, but how can they be set? There doesn't seem to be an API to do so.

That's right. The idea is to build out that as and when need arises. 

You probably noticed the Writer (writer.rs) having a builder pattern. Feel free to make a PR adding it, or i can get to it soon.

**Comment by algesten** [comment]
Fixed by #543
