### ISSUE TITLE
Allow determinstic sorting of candidates in their SDP representation

### ISSUE THREAD

**Issue by thomaseizinger** [algesten/str0m#556]
Upstream issue: https://github.com/firezone/firezone/pull/6200

Essentially, what is happening is that - because `foundation` is a hash - the lexical sort-order of candidates isn't stable in regards to their priority. It would be nice if it were!

**Comment by algesten** [comment]
So you're using `to_sdp_string` and that sort order is not lexically the same as the priority?

**Comment by thomaseizinger** [comment]
> So you're using `to_sdp_string` and that sort order is not lexically the same as the priority?

Correct!

**Comment by thomaseizinger** [comment]
Because it is hashing the IP address and port which is different and I guess completely "randomises" the hash?

**Comment by algesten** [comment]
Well. It's deterministic in that the same ip/port/proto will result in the same foundation.

**Comment by thomaseizinger** [comment]
> Well. It's deterministic in that the same ip/port/proto will result in the same foundation.

Yes but two sets of candidates might have a different ordering, despite being the same candidates (1 host, 1 srflx, 1 relay for example), simply because their addresses are different.

**Comment by algesten** [comment]
Ok so foundation is 1-32 "ice chars". The hash we produce is 64bit, so `u64::MAX.to_string().len()` is 20, which means we got 12 spare chars. The priority is 32 bit. If we encode as hex we get 8 chars.

Ergo. We could prepend the prio:

`<prio as hex><current foundation>`

**Comment by thomaseizinger** [comment]
> Ok so foundation is 1-32 "ice chars". The hash we produce is 64bit, so `u64::MAX.to_string().len()` is 20, which means we got 12 spare chars. The priority is 32 bit. If we encode as hex we get 8 chars.
> 
> Ergo. We could prepend the prio:
> 
> `<prio as hex><current foundation>`

If that works for you, then I'll do that! :)

**Comment by algesten** [comment]
I suppose we can make foundation calculation pluggable if this runs into problem. We will always have a bunch of leading 0. Can we avoid that? 🤔 

`000000ba483948395893849833`

**Comment by thomaseizinger** [comment]
> I suppose we can make foundation calculation pluggable if this runs into problem. We will always have a bunch of leading 0. Can we avoid that? 🤔
> 
> `000000ba483948395893849833`

I was gonna do:

```rust
format!("{:x}{hash:x}", self.prio().to_be())
```

That being said though, prio is "higher is best" so it actually isn't the sort order I want :sweat_smile: 

Ideally, lexical order gives us host candidates first.

**Comment by algesten** [comment]
Uhm. I think this is getting outside of str0m's realm here.

**Comment by algesten** [comment]
Why not sort the candidates any way you want first, then go to the string representation and preserve order?

**Comment by thomaseizinger** [comment]
> Why not sort the candidates any way you want first, then go to the string representation and preserve order?

Yeah that is what I am doing in the above PR. I just figured it might be something that we want to fix upstream. I'd imagine I am not the only one sorting candidates in their SDP representation.

Funnily enough, I only need this because of a race condition when exchanging candidates. If they are exchanged in a certain order, the connection can run into an ICE timeout if we replace a pflx candidate pair that is in the "attempt" state (because we don't copy the stun requests over to the new candidate pair).

I was able to reproduce this in a unit test in str0m locally and it didn't occur if I first added the host candidate before the srflx candidate. I remembered that we don't want to copy over stun requests from the "attempt" nomination state so I figured, it might better to fix the sort order?

**Comment by algesten** [comment]
In my view, the only "natural" sort order would be priority, and I can see that having priority reflected lexically as a nice-to-have-ish.

Getting a timeout when we replace a peer reflexive with a real candidate seems unfortunate. I don't think we can copy the state over, since some stuff in the STUN requests already sent don't match the replacement. But we should maybe reset the state so that it starts probing it from 0.

**Comment by thomaseizinger** [comment]
> In my view, the only "natural" sort order would be priority, and I can see that having priority reflected lexically as a nice-to-have-ish.

I think making this deterministic is good, so I'll send a PR for that.
