### ISSUE TITLE
Make public API for Candidate::server_reflexive

### ISSUE THREAD

**Issue by morajabi** [algesten/str0m#78]
As I use this project in our production app, I'm going to document which types aren't exposed from the public API of `str0m`.

- [ ] `CandidateKind`
- [ ] `Candidate::new` — cannot create a Server Reflexive candidate in any way

**Comment by algesten** [comment]
Thanks!

**Comment by algesten** [comment]
`CandidateKind` is internal, but we should add a new `Candidate::server_reflexive` as a new public method.
