### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by algesten** [algesten/str0m#88]
![str0m logo margins](https://user-images.githubusercontent.com/227204/226141429-cdfd0484-ad90-431b-91b6-6d0f5206aabb.svg)

**Comment by algesten** [comment]
![str0m logo](https://user-images.githubusercontent.com/227204/226143412-e5acf495-05da-4667-8c65-6d6b25085c74.svg)

**Comment by algesten** [comment]
![str0m logo](https://user-images.githubusercontent.com/227204/226143511-66fe5264-6ab7-47b9-9551-90ba7e155b96.svg)

**Comment by davibe** [comment]
haha, amazing.
